[package]
name = "tauri-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
tauri = "1.0.1"
tauri-runtime = "0.10"
tauri-runtime-wry = "0.10"
egui = { git = "https://github.com/wusyong/egui", branch = "tao" }
epi = { git = "https://github.com/wusyong/egui", branch = "tao" }
egui-tao = { git = "https://github.com/wusyong/egui", branch = "tao", features = ["epi"] }
egui_glow = { git = "https://github.com/wusyong/egui", branch = "tao" }
tao-glutin = { git = "https://github.com/wusyong/glutin", branch = "tao", version = "0.1.0" }
glow = "0.11"
rand = "0.8"

[dev-dependencies]
tauri = { version = "1.0.1", features = ["dialog-message"] }

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.15", features = [ "v3_20" ] }

[[example]]
name = "basic"
path = "examples/basic/main.rs"
