[package]
name = "tauri-egui"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
tauri = { path = "../tauri/core/tauri" }
tauri-runtime = { path = "../tauri/core/tauri-runtime/" }
tauri-runtime-wry = { path = "../tauri/core/tauri-runtime-wry/" }

[dependencies]
tauri = "1.0"
tauri-runtime = "0.9"
tauri-runtime-wry = "0.9"
egui = { git = "https://github.com/wusyong/egui", branch = "tao" }
epi = { git = "https://github.com/wusyong/egui", branch = "tao" }
egui-tao = { git = "https://github.com/wusyong/egui", branch = "tao", features = ["epi"] }
egui_glow = { git = "https://github.com/wusyong/egui", branch = "tao" }
tao-glutin = { git = "https://github.com/wusyong/glutin", branch = "tao", version = "0.1.0" }
glow = "0.11"
once_cell = "1.8"
rand = "0.8"

[dev-dependencies]
tauri = { version = "1.0", features = ["dialog-message"] }

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.15", features = [ "v3_20" ] }

[[example]]
name = "basic"
path = "examples/basic/main.rs"
