[package]
name = "tauri-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
tauri = { version = "1.0", git = "https://github.com/tauri-apps/tauri" }
tauri-runtime = { version = "0.10", git = "https://github.com/tauri-apps/tauri"}
tauri-runtime-wry = { version = "0.10", git = "https://github.com/tauri-apps/tauri"}
egui = { git = "https://github.com/wusyong/egui", branch = "new" }
eframe = { git = "https://github.com/wusyong/egui", branch = "new" }
egui-winit = { git = "https://github.com/wusyong/egui", branch = "new" }
egui_glow = { git = "https://github.com/wusyong/egui", branch = "new" }
glutin = { git = "https://github.com/wusyong/glutin", branch = "new" }
glow = "0.11"
rand = "0.8"
raw-window-handle = "0.5"

[dev-dependencies]
tauri = { version = "1.0", git = "https://github.com/tauri-apps/tauri",  features = ["dialog-message"] }

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.15", features = [ "v3_20" ] }

[[example]]
name = "basic"
path = "examples/basic/main.rs"
